# Site settings
title: bshaw.io
email: brian.b.shaw@gmail.com
description: "Just another collection of 1s and 0s that most of the Ineternet will nerver see. I will try to post things I find useful / interesting here."
baseurl: ""
url: "http://bshaw.io"
username: bshaw

# Build settings
markdown: kramdown
permalink: pretty

timezone: America/Indiana/Indianapolis

include: [".well-known"]
