# Site settings
title: bshaw.io
email: bshaw@protonmail.com
description: Brian Shaw
baseurl: ""
url: "http://bshaw.io"
username: bshaw

# Build settings
markdown: kramdown
permalink: pretty

timezone: Europe/London

include: [".well-known"]

plugins:
  - jekyll-redirect-from
